services:
  - name: shoestoreFrontEnd
    type: web
    buildCommand: npm install && npm run build
    envVars:
      - key: REACT_APP_BACKEND_URL
        value: https://shoestorebackend.onrender.com
